services:
  admin-auth-service:
    build: .
    container_name: admin-auth-service
    restart: always
    env_file:
      - .env
    ports:
      - "8005:8005"

    networks:
      - dhwaniastro-net


networks:
  dhwaniastro-net:
    external: true
