services:
  user-auth-service:
    build: .
    container_name: user-auth-service
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@dhwaniastro-postgres:5432/astro
      NODE_ENV: production
      PORT: 8006
    ports:
      - "8006:8006"
    cpus: 0.7
    networks:
      - dhwaniastro-net

networks:
  dhwaniastro-net:
    external: true